### ISSUE TITLE
Extensible plugins framework for cloud services (e.g. FTP, SMB, Drive, Dropbox, One Drive)

### ISSUE THREAD

**Issue by afollestad** [afollestad/cabinet-issue-tracker#1]

**Comment by afollestad** [comment]
OneDrive has an API now, too

**Comment by SgtChrischi** [comment]
I'd love to see SMB-Feature, too!

**Comment by davidedellai** [comment]
You can read Google drive folders?? How??

**Comment by afollestad** [comment]
Google Drive API.

Have you not used QuickPic?

**Comment by davidedellai** [comment]
afollestad can we get in touch via hangout or something else please? I need your help to do this kind of thing. add me on google+ or send me an email please. dellai.davide@gmail.com

**Comment by afollestad** [comment]
@plusCubed I thought of some cool stuff related to this issue for the future (bugs are obviously higher priority right now):

Cloud services can come as plugins that are separate installable apps. The main app will link to them if the user tries to add an account, while the plugin isn't installed.

Each plugin will contain an exported Service, the main app will be able to bind to that Service in order to interact with it. The services will all implement an interface so they all use the same set of methods (e.g. `listFiles`). The services will stay running whenever a connection is active, similar to how SFTP currently works.

Using plugins will prevent the main app from becoming too large. I think we can also move SFTP to a service plugin when we begin doing this.

**Comment by afollestad** [comment]
We could probably use this to offload SD card and USB OTG support from the main app for people that don't need that anyways too. @plusCubed

**Comment by hyl** [comment]
Like the sound of this, @afollestad! Would you make the plugin documentation publicly available so people can make their own plugins?

**Comment by afollestad** [comment]
Yep! That's the plan

**Comment by hyl** [comment]
Awesome! :+1:

**Comment by afollestad** [comment]
I've started the basic framework, it's working out very well so far.

**Comment by afollestad** [comment]
![screen shot 2015-04-13 at 2 22 29 pm](https://cloud.githubusercontent.com/assets/1820165/7123559/8ec111ca-e1e8-11e4-8772-25d500ca77e5.png)

@plusCubed

**Comment by afollestad** [comment]
E.g.:

![screen shot 2015-04-13 at 2 25 26 pm](https://cloud.githubusercontent.com/assets/1820165/7123607/f630bf36-e1e8-11e4-8190-d5c455ccab52.png)

@plusCubed you can see this in action if you clone the framework repository and run the sample in an emulator or on your phone.

**Comment by afollestad** [comment]
This issue was replaced with https://github.com/afollestad/cabinet-issue-tracker/issues/181
