### ISSUE TITLE
Compress bread crumbs for SD card path

### ISSUE THREAD

**Issue by afollestad** [afollestad/cabinet-issue-tracker#100]

**Comment by afollestad** [comment]
@arkon annnd it would be helpful if you could test this

**Comment by arkon** [comment]
@afollestad Shows "Root > Storage > SD Card" for me.

Launching the app (with or without saved location) also makes it go to "Root > Storage > Emulated > Internal Storage" (i.e. it isn't compressed). It's fine if you navigate to it from the nav drawer though.

**Comment by afollestad** [comment]
@arkon hmm, very weird.

I wish I had an easy way to test this myself too.

**Comment by afollestad** [comment]
@arkon I think I found a way to mount an SD card to a path in the emulator.

**Comment by arkon** [comment]
@afollestad Isn't it pretty complicated?

**Comment by afollestad** [comment]
Not as complicated as I thought, haven't tested it yet: http://www.jayway.com/2009/04/22/working-with-sd-cards-in-the-android-emulator/

**Comment by afollestad** [comment]
It didn't quite work. Dammit.

**Comment by afollestad** [comment]
Should work now in theory

**Comment by afollestad** [comment]
Works officially now
