### ISSUE TITLE
Weird folder deletion issue

### ISSUE THREAD

**Issue by afollestad** [afollestad/cabinet-issue-tracker#104]
Their post content:

"Screen gets stuck over here... :/ doesn't delete anything even after 15 minutes. So it's not UI problem. Nexus 4 (5.0.1 Stock Lollipop)"

![15 - 1](https://cloud.githubusercontent.com/assets/1820165/6271328/96dd1760-b825-11e4-80e3-46cb450e1d43.png)

**Comment by afollestad** [comment]
@plusCubed have you been able to reproduce this issue? Deletion seems to be working fine on my end. It looks like he was deleting folders from selection mode.

**Comment by plusCubed** [comment]
@afollestad I can't reproduce either. Hmm... weird.

**Comment by afollestad** [comment]
Can't reproduce
