### ISSUE TITLE
Old SD card folders get stuck in the nav drawer

### ISSUE THREAD

**Issue by afollestad** [afollestad/cabinet-issue-tracker#108]
If the SD card path changes, the app doesn't remove the old path and it gets stuck in the user's pins.

**Comment by afollestad** [comment]
@plusCubed @arkon if you guys have installed newer builds than what's on Google Play, I recommend that you clear data for the app since some ordering stuff for the navigation drawer was changed (pins have 'order' integers saved with them in newer builds, removable ones were getting the wrong number).

**Comment by afollestad** [comment]
Should be fixed

**Comment by arkon** [comment]
@afollestad Thanks for the heads up.
