### ISSUE TITLE
Wrong CAB theme in dialogs on pre-Lollipop

### ISSUE THREAD

**Issue by afollestad** [afollestad/cabinet-issue-tracker#11]
On KitKat:

![1](https://cloud.githubusercontent.com/assets/1820165/6140428/35a08faa-b15d-11e4-977b-7fb97bcc9f0a.png)

On Lollipop:

![2](https://cloud.githubusercontent.com/assets/1820165/6140431/384353e6-b15d-11e4-84c6-b0692d19174c.png)

**Comment by afollestad** [comment]
@plusCubed should we just close this? I don't think there's any solution I haven't tried that works to fix this for older API levels.

**Comment by plusCubed** [comment]
@afollestad I think I *might've* found a solution. Don't close this just yet.

**Comment by afollestad** [comment]
Alright cool, everything else is basically ready for a release now

**Comment by afollestad** [comment]
This is pretty similar but caused by something else: https://github.com/afollestad/cabinet-issue-tracker/issues/164
