### ISSUE TITLE
the Keystore's login password should be removed from github

### ISSUE THREAD

**Issue by letroll** [afollestad/cabinet-issue-tracker#112]
Hello, I'm not sure it's your personal login,password and keystore, but I've seen multiple repository on github with that data. 

May be it's not too late to remove it.

**Comment by afollestad** [comment]
There is no public repository to remove it from.

**Comment by arkon** [comment]
https://github.com/search?q=aidan1995&type=Code&utf8=✓

**Comment by afollestad** [comment]
Well, yeah, there's not much I can do about those unless I were to contact
them all to take them down. I'm not sure if this guy realizes it's no
longer open source.

**Comment by afollestad** [comment]
I just contacted the people in those search results but there's no
guarantee they'll respond (other than Shirwa who I know personally).
