### ISSUE TITLE
Floating Action Button actions obstructed in landscape.

### ISSUE THREAD

**Issue by cmikeh2** [afollestad/cabinet-issue-tracker#113]
When in landscape and the floating action button is pressed to create files, the top generic file option is obstructed because the z-height of the toolbar is greater than the action button.

**Comment by afollestad** [comment]
Hmm. You must have a very small screen.

The only thing that can be done about this right now is turning off the "Current Path" option while in landscape. I'll see if there's any other ways to improve this.

**Comment by afollestad** [comment]
AFAIK, there's not really a good solution to this. A lot of apps use the same FAB library that we're using.

**Comment by afollestad** [comment]
Someone posted this on Google+:

![15 - 1](https://cloud.githubusercontent.com/assets/1820165/7123837/9560832e-e1ea-11e4-8450-59db99b71e25.png)

Re-opened the issue.

**Comment by afollestad** [comment]
@plusCubed we could solve this by using a horizontal FAB menu, not sure if that library lets you easily switch between horizontal and vertical though. If it's a layout thing, we could have a separate `include`d layout for portrait/landscape.

**Comment by plusCubed** [comment]
@afollestad I removed the horizontal menu when modifying the library (because I didn't want to deal with it :P). I think the easiest fix right now for larger devices would be to move the fab in front of the toolbar. I can work on re-adding the horizontal bar after I'm done with the fast scrolling.

**Comment by afollestad** [comment]
@plusCubed oh yeah, good idea, sounds good

**Comment by afollestad** [comment]
I'm gonna consider this fixed for now.
