### ISSUE TITLE
Custom Tabs 

### ISSUE THREAD

**Issue by ALIRAQI** [afollestad/cabinet-issue-tracker#115]
Hi 
Can please add Custom tab feature with it users add tabs to different folder for quick access it should appear under external storage option 
Check the picture
http://s10.postimg.org/uho061kcp/Pics_Art_1424741109277.png 

This the only feature I miss in this awesome app 

Thanks

**Comment by afollestad** [comment]
The divider separates custom shortcuts and shortcuts that cannot be removed.

The shortcuts below that line are custom. You can bookmark folders there from the 3-dot menus within lists.
