### ISSUE TITLE
Changelog text causes horizontal scrolling in dialog box

### ISSUE THREAD

**Issue by karlding** [afollestad/cabinet-issue-tracker#118]
The changelog text overflows along the x-axis, causing the Changelog Dialog to overflow horizontally, and becomes horizontally scrollable.

![Screenshot 1](http://i.imgur.com/MHS98yL.png "All the way left")
![Screenshot 2](http://i.imgur.com/0DQmVnX.png "All the way right")

I'm using a Nexus 5 running Stock Lollipop (rooted).

**Comment by afollestad** [comment]
There's not much I can do about this as far as I know. That's just a web view displaying HTML content, your phone choose to make it horizontally scrollable.

**Comment by afollestad** [comment]
But I'll see if there's any possible solutions.
