### ISSUE TITLE
FAB - tapping once, then quickly tapping twice results in no file menu cover-up.

### ISSUE THREAD

**Issue by CalH00** [afollestad/cabinet-issue-tracker#121]
Yeah,the title is crap, but I just wanted to report a quick bug.
When tapping the FAB to expand it and then quickly tapping it twice, it results in the file menu not getting covered by that grey layer.
![screenshot_2015-03-04-23-31-46](https://cloud.githubusercontent.com/assets/7706853/6495073/10e41d28-c2c7-11e4-9b81-1e056dfa188f.png)

**Comment by afollestad** [comment]
I've been able to reproduce this once or twice but it's very hard to reproduce with regular use, lol

**Comment by arkon** [comment]
Same, doesn't really seem like a huge issue to me.

**Comment by afollestad** [comment]
Yeah, I'm gonna close this for now. Users who aren't purposely trying to find issues won't find this.
