### ISSUE TITLE
Resources#getDrawable() deprecated and replaced with a new variation

### ISSUE THREAD

**Issue by afollestad** [afollestad/cabinet-issue-tracker#122]
https://plus.google.com/+AlanViverette/posts/YHy5drbz3oN

**Comment by dvhien90** [comment]
Used :
Utils.getResources(id);

**Comment by afollestad** [comment]
I don't think `Utils` is a class for this. I'll be using the new Compat method from the support library.

**Comment by afollestad** [comment]
To be more specific: https://plus.google.com/+AlanViverette/posts/YHy5drbz3oN
