### ISSUE TITLE
FAB sometimes covers list contents

### ISSUE THREAD

**Issue by arkon** [afollestad/cabinet-issue-tracker#123]
If the list has just enough items to fit on the screen without needing to scroll, the user cannot scroll to hide the FAB, and as such it remains on top of the last item. 

Potential fix: have extra space at the bottom of the list similar to the Gmail app.

**Comment by afollestad** [comment]
Yeah, I saw that a few days ago and tried making a fix but it's a bit more
complicated than I thought with the time I have aside from class at the
moment.

The padding at the bottom of the list needs to equal the height of the FAB
plus the top and bottom margin. You have to wait until it's drawn using a
Tree Observer, and get the FAB that's inside the FAB menu view.
