### ISSUE TITLE
Issues with new breadcrumbs system in Project WD40

### ISSUE THREAD

**Issue by plusCubed** [afollestad/cabinet-issue-tracker#124]
1. Search cannot be exited.
2. Back button currently just goes up a folder (intentional but meant to be temporary (forgot :P))
    Solution: keep a list of visited folders. Go up the chain when pressing back.

**Comment by afollestad** [comment]
I solved the search issue by keeping search within the same active fragment it's started in.

**Comment by afollestad** [comment]
Gonna close this in favor of separate issues
