### ISSUE TITLE
Intent filters for selecting files doesn't work for some apps

### ISSUE THREAD

**Issue by rsmything** [afollestad/cabinet-issue-tracker#131]
Hello,

You need to add the ability to select files in other applications using Cabinet. For example, now it is impossible to select the ringtone of the alarm as this can be done using [ES Explorer](https://play.google.com/store/apps/details?id=com.estrongs.android.pop).

**Comment by afollestad** [comment]
You already can, e.g. in Gmail. Some apps don't support it correctly for some reason.

**Comment by afollestad** [comment]
I updated the title to more accurately reflect what you mean.

**Comment by rsmything** [comment]
OK, thx

**Comment by afollestad** [comment]
Could you give an example of an app that doesn't let you select a file through Cabinet?

I can't and don't use custom ringtones on my Nexus 6.

**Comment by afollestad** [comment]
This should be fixed but I don't have an easy way to test it.

**Comment by rsmything** [comment]
In the Clock app(native android 5.1 app), when I want to change ringtone.

**Comment by afollestad** [comment]
I don't get options for third party apps there, only built in Ringtones.
Cabinet can't be used there.

**Comment by rsmything** [comment]
If ES Explorer is installed, then pressing the ringtone, the system offers a choice of applications to install ringtone^
![screenshot_2015-04-03-11-44-13](https://cloud.githubusercontent.com/assets/11719983/6979128/496dfb26-d9f8-11e4-9db1-4a7279e99193.png) ![screenshot_2015-04-03-11-44-18](https://cloud.githubusercontent.com/assets/11719983/6979129/4abc9c1c-d9f8-11e4-8e95-e01b4fdfa3c7.png)

**Comment by afollestad** [comment]
Done
