### ISSUE TITLE
Cabinet text editor isn't able to save files in root/ext-storage directories

### ISSUE THREAD

**Issue by shubhamkrm** [afollestad/cabinet-issue-tracker#132]
I can create new files using Cabinet but when I try to write something into it using the Cabinet text editor, it doesn't allow me to save my work, and gives the following error: "superuser not available".

**Comment by bugaevc** [comment]
I have this issue as well.
Cabinet Text Editor isn't able to save a text file even in internal storage for me giving the same error message.
