### ISSUE TITLE
Switch to new FAB library

### ISSUE THREAD

**Issue by afollestad** [afollestad/cabinet-issue-tracker#133]
https://github.com/Clans/FloatingActionButton

**Comment by plusCubed** [comment]
Hmm... I'm not sure about this. I don't see some things I implemented in the cabinet one (elevation on touch, smooth hiding/showing, etc). I'll see if I can work on submitting a pull request or something for those.

**Comment by afollestad** [comment]
Cool, sounds good

**Comment by afollestad** [comment]
I think this one is unnecessary for now
