### ISSUE TITLE
Switch back to using getLayoutPosition() and other RV methods once there's a less buggier version than 22.0.0

### ISSUE THREAD

**Issue by afollestad** [afollestad/cabinet-issue-tracker#136]
https://github.com/afollestad/cabinet/commit/20a2d4d759c884d3d631447bf61db7bff65e99b5

**Comment by plusCubed** [comment]
Related? I'll just put this here: https://code.google.com/p/android/issues/detail?id=162753

**Comment by plusCubed** [comment]
We've switched to v22.1.0, but the Google Code issue still says FutureRelease. I wonder if they just haven't updated their page yet. Should we close this issue and just keep an eye on it?
(https://code.google.com/p/android/issues/detail?id=162753)
