### ISSUE TITLE
Add Movies to the sidebar and customization

### ISSUE THREAD

**Issue by Keavon** [afollestad/cabinet-issue-tracker#138]
I love the DCIM, Download, Music, and Pictures buttons in the sidebar, but I'd also like to see Movies added to the list.

Also adding a setting to enable/disable some of those options would be useful so people with smaller screens who don't use some of those items can hide them.

Custom folders to pin to that list may be also something to consider.

Also, changing "Download" to "Downloads" would improve consistency with the plural options "Pictures" and "Music" (even though the folder itself is not plural, that isn't that doesn't really matter).

**Comment by afollestad** [comment]
The default ones are just the basics. You can add (Bookmark option on folders) or remove (long press bookmarks) your own.

**Comment by Keavon** [comment]
Oh, I did not notice that those already existed. Already implemented, then!
