### ISSUE TITLE
Vector file and folder icons

### ISSUE THREAD

**Issue by HeinrichReimer** [afollestad/cabinet-issue-tracker#14]
On my Nexus 7 in grid mode the folder icons look blurry.
Please add high res drawables and/or use androids new [`VectorDrawable`][1] for 5.0+

[1]: https://developer.android.com/reference/android/graphics/drawable/VectorDrawable.html

**Comment by HeinrichReimer** [comment]
I attached some screenshots:
![screenshot_2015-02-11-21-11-14](https://cloud.githubusercontent.com/assets/5065698/6155372/13b53af4-b233-11e4-8979-cb2cb2ef8999.png)
![screenshot_2015-02-11-21-11-10](https://cloud.githubusercontent.com/assets/5065698/6155373/13bc2ba2-b233-11e4-92c1-a834bd4843e5.png)

**Comment by afollestad** [comment]
Unfortunately vector drawables cannot be used for this, these folder icons are taken from the Android Asset studio, vectors require you to draw shapes with math (which is what makes them scalable without losing quality). But I'll try to get larger icons in there to see if that helps.

**Comment by HeinrichReimer** [comment]
If i find some time I can convert the SVGs from polymer source to `VectorDrawables`

**Comment by plusCubed** [comment]
@HeinrichReimer @afollestad Found a way, I'll be implementing this.

**Comment by afollestad** [comment]
@plusCubed awesome, sounds good.

Issue https://github.com/afollestad/cabinet-issue-tracker/issues/5 is the next highest priority issue before an update can go out.

**Comment by plusCubed** [comment]
@HeinrichReimer Done.
@afollestad OK, I'll take a look at that.

**Comment by afollestad** [comment]
@plusCubed wow that was fast.

Awesome, thanks.

**Comment by afollestad** [comment]
With people complaining about the fact that the app is 23MB, I'm not sure if vectorizing all of the icons would be the best idea anymore

**Comment by plusCubed** [comment]
@afollestad I would think vectors will help fix the problem (since they're just text files instead of giant images)?.... Either way, only lollipop supports it. I'm wondering if it's worth the effort to use a library like [MrVector](https://github.com/telly/MrVector) to backport VectorDrawables to <5.0. Then we can essentially remove all the images.

**Comment by afollestad** [comment]
Oh yeah, that would actually be a great idea

**Comment by plusCubed** [comment]
@afollestad OK, I'll do that then.

**Comment by arkon** [comment]
@afollestad @plusCubed Another idea is to only have a "core" set of icons packaged in the APK, and additional vector and/or image files can be downloaded and cached later on?

**Comment by plusCubed** [comment]
@arkon Good idea, but that would involve more complicated things. I'll open another issue for that after finishing this one (if file size remains significant).

**Comment by afollestad** [comment]
A file manager shouldn't have to fetch more resources, that's something I would reserve for games.

**Comment by plusCubed** [comment]
I replaced the file icons with vectors by using the MrVector library. Unfortunately, the overall file size didn't change much, and after examining all the image files combined, it is not surprising: they only use 500KB. Removing images is not going to be the solution for file size. 

Anyway, there are still a few icons I need to change to vector (the custom ones).

**Comment by afollestad** [comment]
Done, right @plusCubed?
