### ISSUE TITLE
Play Audio files in background

### ISSUE THREAD

**Issue by tunjos** [afollestad/cabinet-issue-tracker#140]
Aidan.sendRequest(audio.playinbackground);
while(Cabinet Beta == Background){
audio.play++;
}

**Comment by plusCubed** [comment]
Umm... do you mean to create an audio player? That's not what this project's for.

**Comment by afollestad** [comment]
He means the same way Solid Explorer beta does it.  It is a nice feature, but it does seem a bit excessive for a file manager, when Android is built to allow apps to work together.

**Comment by plusCubed** [comment]
@afollestad Yeah, that's what I meant to say - I don't think it's necessary when there are audio players out there (including Google Play Music, installed on every device by default).

**Comment by afollestad** [comment]
Yeah, I agree

**Comment by tunjos** [comment]
Yea. I see an internal audio player. But it shuts down when I leave its  context.
A way to have this running in the background would be nice.
Maybe a Service would do.
This could be useful for some files like voice recordings etc Not just music.

**Comment by afollestad** [comment]
Hmm, good point. I'll leave this issue open.

**Comment by plusCubed** [comment]
That "internal" audio player is actually just Google Play Music... I don't think there's any way to keep that in the background?

**Comment by afollestad** [comment]
It is, Play Music shows it as a dialog unless you start it from within their app. I could see where a background-supported audio player could come in useful in some situations.

**Comment by tunjos** [comment]
I get the point.I Just realized its Google Play Music.

**Comment by afollestad** [comment]
This is done for the next update

**Comment by afollestad** [comment]
This is live in 1.9.2.8

It's on APK Mirror already: http://www.apkmirror.com/apk/aidan-follestad/cabinet/cabinet-1-9-2-8-2-android-apk-download/

**Comment by tunjos** [comment]
#Genius
Good Job.
