### ISSUE TITLE
Unable to move to external sdcard

### ISSUE THREAD

**Issue by philljoynes** [afollestad/cabinet-issue-tracker#142]
When I try to move a file/s to the external sd Card, I get an error saying "Failed to rename/move this file: Unknown error".

 I am using android 5.0.2 temasek rom on Samsung Galaxy Note 3.

**Comment by philljoynes** [comment]
I can copy the same files successfully.

**Comment by afollestad** [comment]
This will be resolved once https://github.com/afollestad/cabinet-issue-tracker/issues/186 is done
