### ISSUE TITLE
Ability to mount /system and RW

### ISSUE THREAD

**Issue by philljoynes** [afollestad/cabinet-issue-tracker#143]
It would be nice to have the ability to mount system as read write.

**Comment by plusCubed** [comment]
Question: to do what? All file operations should mount and unmount system automatically. Do you have a specific bug where mounting is not working?

**Comment by philljoynes** [comment]
Hi Daniel,

I was not aware of this feature working in this way, that is brilliant.  I
am used to doing it manually in es file explorer, so wrongly assumed you
would do the same with Cabinet.  Sorry for wasting your time!

Phill

**Comment by plusCubed** [comment]
@philljoynes No problem. If you have any specific folders or problems in your usage with the mounting, feel free to open another issue.

**Comment by afollestad** [comment]
Yeah, I tried to make Cabinet as minimal as possible from the start so I avoided manual mount options.

**Comment by philljoynes** [comment]
It it's far better that way. I guess I wrongly came in with a preconceived
way of doing it that meant I was confused.  Thanks for your great work!
