### ISSUE TITLE
Dynamic theme colors for CheckBoxes in Toolbar sub menus

### ISSUE THREAD

**Issue by afollestad** [afollestad/cabinet-issue-tracker#146]
In Material Dialogs, edit texts and other UI elements have dynamic colors set to match a widget theme color. This is done on API 21 and above using tint lists, e.g. RadioButton.setButtonTintList(ColorStateList.valueOf(color)). Below Lollipop, setColorFilter() is used on the respective view's drawable. The tint colors should match the user's theme accent color.

**Comment by afollestad** [comment]
In the upcoming release of Material Dialogs, I mean, not the current.

**Comment by afollestad** [comment]
@plusCubed I was trying to find a solution for the checkboxes in menu items but couldn't find one.

Oddly enough, there's no direct way to get views inside of menu items. I tried looking into the classes to see if reflection could be used, but didn't see any related fields. Action Providers and Action Views only work for action items not in the overflow.

**Comment by plusCubed** [comment]
@afollestad I managed to get the ListView from the drop down menu using reflection on my Nexus 5 running 5.1 (haven't tested anywhere else). I'm going to sleep now - I've pushed the code if you want to finish it up (cycling through the views, finding the checkbox, tinting them).

**Comment by afollestad** [comment]
@plusCubed  wow, cool, didn't think it was possible at this point. Thanks, I'll do that in a bit.

**Comment by afollestad** [comment]
Done

**Comment by arkon** [comment]
The radio and checkboxes in the sorting and grid size menus aren't themed.

**Comment by afollestad** [comment]
This might be a bit harder because the fact that they aren't, means the callback we are currently using to perform reflection on the overflow menu's ListView, is not being called for sub menus.

**Comment by afollestad** [comment]
Actually, nevermind, the callback (`onMenuOpened()` in `MainActivity`) is still called for sub menus, but it's not quite as straightforward to get a hold of the list view inside that sub menu. Especially because sub menus get displayed as list dialogs (wrongly themed list dialogs at that: https://github.com/afollestad/cabinet-issue-tracker/issues/139) on older devices or Android versions.

**Comment by plusCubed** [comment]
Done.
