### ISSUE TITLE
Browser Upload Selecting Folders

### ISSUE THREAD

**Issue by danielhickman** [afollestad/cabinet-issue-tracker#153]
I am having this problem when uploading an APK to APKMirror. My app extractor extracts to a folder that I had to navigate to in the last version of Cabinet. In this version (1.9.2.7), it chooses the folder instead of navigating to it.

**Comment by afollestad** [comment]
I already uploaded the update to APK Mirror last night but it didn't go out
yet lol.

I'll look at this later though.

**Comment by afollestad** [comment]
Fixed

**Comment by afollestad** [comment]
This fix is live in 1.9.2.8

It's on APK Mirror already: http://www.apkmirror.com/apk/aidan-follestad/cabinet/cabinet-1-9-2-8-2-android-apk-download/

**Comment by danielhickman** [comment]
Thanks!
