### ISSUE TITLE
You can not go to a folder to select an audio file

### ISSUE THREAD

**Issue by rsmything** [afollestad/cabinet-issue-tracker#154]
when i tapped by folder^
![screenshot_2015-04-07-21-10-55](https://cloud.githubusercontent.com/assets/11719983/7027786/fdf90354-dd6a-11e4-9057-56f501e2f2c5.png)

**Comment by afollestad** [comment]
I believe this is the same thing, if not related to https://github.com/afollestad/cabinet-issue-tracker/issues/153

**Comment by afollestad** [comment]
Fixed
