### ISSUE TITLE
Changelog pop-up design fix (in text box) 

### ISSUE THREAD

**Issue by ente3000** [afollestad/cabinet-issue-tracker#155]
Background = dark grey, as around the log

**Comment by afollestad** [comment]
This is dependent on what theme you're using in the settings.

**Comment by afollestad** [comment]
The white part in there is an embedded web browser used to display an HTML changelog, that cannot be easily changed.

**Comment by arkon** [comment]
Could you use [`WebView.evaluateJavaScript`](http://developer.android.com/reference/android/webkit/WebView.html#evaluateJavascript(java.lang.String, android.webkit.ValueCallback<java.lang.String>)) to inject a simple style tag to make the background dark and all the text white?

**Comment by afollestad** [comment]
It's probably possible, but not sure how much it supports for security reasons.

**Comment by afollestad** [comment]
I guess it is a full fledged mini browser so it should in theory work.

**Comment by afollestad** [comment]
I am loading from a local HTML file so I wonder if putting a style tag in that would work, I'll try it.

**Comment by afollestad** [comment]
It works.

**Comment by arkon** [comment]
Yay! :smile:

**Comment by afollestad** [comment]
Done, in the code base for the next update.

Both themes will match the dialog background, and it will have better padding to look symmetrical with the dialog title.

**Comment by afollestad** [comment]
This is live in 1.9.2.8

It's on APK Mirror already: http://www.apkmirror.com/apk/aidan-follestad/cabinet/cabinet-1-9-2-8-2-android-apk-download/
