### ISSUE TITLE
Action bar icons dark on dark instead of white on dark (Light theme)

### ISSUE THREAD

**Issue by JacobMWilliams** [afollestad/cabinet-issue-tracker#159]
Droid Maxx, stock 4.4.4. It has capacitive nav keys if that matters.

**Comment by afollestad** [comment]
This really shouldn't be possible, the share and delete icons are both white images themselves. Very odd.

**Comment by JacobMWilliams** [comment]
Are they PNGs with an alpha channel?

**Comment by afollestad** [comment]
Nope, 100% opacity. It's odd that they work fine for me, the guy who helps out with dev, and lots of other people. This is a very rare case :o

**Comment by afollestad** [comment]
Reported as fixed via Google+
