### ISSUE TITLE
Fast scrolling

### ISSUE THREAD

**Issue by onchu** [afollestad/cabinet-issue-tracker#160]
Too many file managers are missing this feature. Imo, it is an absolute must handy tool to scroll folders containing thousands of pictures. Consider implementing it as it's really really essential.

**Comment by afollestad** [comment]
Currently, this is not possible. Cabinet does not use ListViews, it uses RecyclerViews, which by default do not support fast scrolling (the thumb scroll thing).

**Comment by plusCubed** [comment]
This perhaps: https://github.com/danoz73/RecyclerViewFastScroller

**Comment by afollestad** [comment]
Oooh, cool

**Comment by afollestad** [comment]
@plusCubed currently that library can't be used because it will override our scroll listener that's used to hide the FAB

**Comment by plusCubed** [comment]
@afollestad Found a way around it: we just call the fast scroller scroll listener manually in our own scroll listener.

**Comment by afollestad** [comment]
@plusCubed good idea. 

Someone emailed me about a jump to bottom or jump to top option, I think this will resolve the need for that.

**Comment by plusCubed** [comment]
@afollestad Yep, I think this will. I'm working on modifying the library to our needs - I really don't like the way the library is structured and implemented. The scrolling is not smooth at all and there are extra features we don't need.

**Comment by afollestad** [comment]
@plusCubed awesome, looking forward to it.

**Comment by plusCubed** [comment]
I pushed the code so far. There are still lots of bugs and issues (e.g. color, touch area, cannot be seen under toolbar, no code to hide it when not scrolling, etc), but it's working. I haven't seen any other app with an aesthetically pleasing smooth fast scroller (not jumping to the next item), so this is unique, though I'm not sure it's functionally better, now that I see it in action (it's a bit harder to see the file file names when the list is smoothly scrolling, as opposed to having the names in one spot, jumping to the next item).

**Comment by afollestad** [comment]
@plusCubed looking good so far. I fixed it being under the toolbar by using a different hide algorithm that now applies padding to the RecyclerView and FastScroller as you scroll.

**Comment by plusCubed** [comment]
@afollestad OK, I added hiding/showing the scrollbar, a few more changes to the color and height of the handle, and the scroll listener activation for the other components (FAB and toolbar hide/show). I believe everything should be done now (yay!). We can open new issues later if they come up.
