### ISSUE TITLE
Replace folder name with 'Cabinet' at the top of the action bar.

### ISSUE THREAD

**Issue by CalH00** [afollestad/cabinet-issue-tracker#17]
The title says it all. Now that you have added an extended action bar with those path... arrow... thingies... Whatever they're called again, I don't think it's necessary to still have the name of the current folder next to the hamburger icon.

**Comment by afollestad** [comment]
Good idea. When the bread crumbs are enabled I'll just show the app name.

**Comment by afollestad** [comment]
Done

**Comment by CalH00** [comment]
Cool :-).
