### ISSUE TITLE
Change where version information is

### ISSUE THREAD

**Issue by imcilwraith** [afollestad/cabinet-issue-tracker#170]
As per the new Material Design guidelines, (http://www.google.com/design/spec/patterns/settings.html#settings-flow-structure)

The version information should be placed under a help section-
Items that do not belong in Settings:
Contain information about the app, such as a version number 
(Move these to a Help screen)

**Comment by afollestad** [comment]
Good idea, fixed for the next update.

I moved the about dialog to a "Help & feedback" dialog and added some additional information there.
