### ISSUE TITLE
Changelog popup

### ISSUE THREAD

**Issue by Vegownz** [afollestad/cabinet-issue-tracker#176]
When you start the new version of the program, you get a changelog popup. If you go back and run the program again, you get another changelog popup over the previous one, etc.

**Comment by afollestad** [comment]
Already fixed

**Comment by Vegownz** [comment]
Well, bug is still there for the version 1.9.4.0-dev3. (You have to go back, by pressing the HOME button, and then run the app)

**Comment by afollestad** [comment]
Officially fixed now
