### ISSUE TITLE
Fast scroller is blowing up the LogCat :o

### ISSUE THREAD

**Issue by afollestad** [afollestad/cabinet-issue-tracker#178]
![screen shot 2015-04-17 at 9 48 00 am](https://cloud.githubusercontent.com/assets/1820165/7204336/e58d8352-e4e6-11e4-9dc9-468f52ac4b8a.png)

**Comment by plusCubed** [comment]
Should be fixed.

**Comment by afollestad** [comment]
It still happens a little

**Comment by plusCubed** [comment]
Completely fixed now.
