### ISSUE TITLE
Action bar buttons ripple size

### ISSUE THREAD

**Issue by CalH00** [afollestad/cabinet-issue-tracker#18]
I just noticed that the overflow button in the action bar has a smaller ripple circle than the other buttons, especially the hamburger icon. Not that big of an issue, but it looks kinda odd.

**Comment by afollestad** [comment]
I can't really change that unfortunately. Android renders the toolbar and it's actions for you.

**Comment by CalH00** [comment]
Okay :-/. Thanks anyways.
