### ISSUE TITLE
Overflow menu/submenus checkbox/radio button tinting gone

### ISSUE THREAD

**Issue by plusCubed** [afollestad/cabinet-issue-tracker#185]
due to AppCompat update I suspect

**Comment by afollestad** [comment]
It appears `onMenuOpened` is not getting invoked anymore

**Comment by afollestad** [comment]
This is 1 of 2 things to fix before 1.9.4.0 is going public.

**Comment by afollestad** [comment]
I actually assigned milestones to every issue to set target release versions.

**Comment by plusCubed** [comment]
Fixed.
