### ISSUE TITLE
Issues with animated app bar covering list items

### ISSUE THREAD

**Issue by afollestad** [afollestad/cabinet-issue-tracker#189]
If you have the app bar collapsed, then navigate into a subfolder that has scrollable contents, the app bar will expand and cover the first item in the list.

The same happens going in the opposite direction sometimes too.

**Comment by afollestad** [comment]
This is a bit difficult to solve, we need to keep the user's scroll position as the app bar expands or collapses. However, we can't assume the list should stay at position 0, since the fragment might have a saved scroll position from a previous state.

**Comment by afollestad** [comment]
This is 2 of 2 things to fix before 1.9.4.0 is going public.

**Comment by plusCubed** [comment]
I fixed #175, but in trying to solve this bug I think I have a better solution for both. I should be able to fix these by tomorrow.

**Comment by afollestad** [comment]
Appears to be fixed
