### ISSUE TITLE
File Filtering is case-sensitive

### ISSUE THREAD

**Issue by git-commit** [afollestad/cabinet-issue-tracker#192]
When using the FILTER menu option and entering e.g. `.Jpg` (Some keyboards do automatic CamelCase) no files are found since the matching seems to be case-sensitive.

Even tough the Linux filesystem is generally case-sensitive, it would be nice to see the filtering work case-insensitive to be more convenient for users.

**Comment by afollestad** [comment]
Part of the issue was the input dialog's input type telling keyboards to capitalize words, keyboards that don't currently do so are not following standards.

But I will have this issue fixed in the next update, thanks.
