### ISSUE TITLE
When the fast scroll track is visible (not animated out), its touch target covers the file menus

### ISSUE THREAD

**Issue by afollestad** [afollestad/cabinet-issue-tracker#194]

**Comment by plusCubed** [comment]
Intentional for minimum touch target of 48dp, though I suppose it could be made clearer that it covers the file menu (I'm not sure making it 48dp wide would look good though)

**Comment by afollestad** [comment]
Oh right, I see. That might not be the most intuitive things to a lot of users, cause of the few-second delay that it takes for the fast scroller to hide itself after the user stops scrolling.

**Comment by afollestad** [comment]
@plusCubed maybe there's a way to hide the fast scroll bar when the user taps (rather than dragging)?

**Comment by afollestad** [comment]
Closing this as it seems fine for now
