### ISSUE TITLE
Pull down to refresh for plugin folders?

### ISSUE THREAD

**Issue by alexsmithfanning** [afollestad/cabinet-issue-tracker#195]
The one similar to Inbox. Or even the one like in Google Now (the horizontal colored bars) to make it easier to refresh the file listing.

**Comment by afollestad** [comment]
Well, this isn't really necessary for most folders since contents are refreshed everytime a folder comes into view again. It's unlikely you'd most people would need to refresh what their currently viewing, files don't tend to change in the background.

**Comment by afollestad** [comment]
Well, this isn't really necessary for most folders since contents are refreshed everytime a folder comes into view again. It's unlikely most people would need to refresh what they're currently viewing, files don't tend to change in the background.

**Comment by afollestad** [comment]
I don't think this is necessary.
