### ISSUE TITLE
Remove name ellipsis truncation "..." or add an option to remove it.

### ISSUE THREAD

**Issue by richarddd** [afollestad/cabinet-issue-tracker#196]
This file browser is the prettiest and most useful view ever had. However, when viewing files in a grid, the file name is ellipsised with "..." which makes it harder to know the file name.

Other file managers such as Es File explorer does not ellipsis the filenames :)

Thank you. Btw, I've supported your development with a few $ :+1:

**Comment by afollestad** [comment]
It can't be completely removed, otherwise the user wouldn't know there's more text after where it gets clipped.

However I will increase the file title while in grid mode to a max of two lines which should help improve the experience there.

And thank you!
