### ISSUE TITLE
Using high grid sizes causes issues on screens that are too small

### ISSUE THREAD

**Issue by afollestad** [afollestad/cabinet-issue-tracker#20]

**Comment by HeinrichReimer** [comment]
Maybe we should limit the maximum column count to somewhat like this:

    Resources resources = context.getResources();
    DisplayMetrics metrics = resources.getDisplayMetrics();
    
    float widthDp = metrics.widthPixels / (metrics.densityDpi / 160f);
    
    int maxColums = (int) Math.floor(widthDp / 144);

and then disabling grid sizes above that value. 144 can be replaced by any other minimum colum width in DPs.

**Comment by afollestad** [comment]
@HeinrichReimer yeah that's a good idea

**Comment by afollestad** [comment]
It's actually easier to just use dimension resources in this case

**Comment by afollestad** [comment]
Done, grid size isn't limited on tablets, but it's limited to 3 on phones. May need to be adjusted for other screen sizes later, but I'm using a Nexus 6 which is obviously big.
