### ISSUE TITLE
Text editor doesn't include changes with saved instance state

### ISSUE THREAD

**Issue by rddck** [afollestad/cabinet-issue-tracker#21]
using the cabinet built in text editor to modify text files and i notice that it reverts to the last saved state each time the screen rotates :s 

as a side note, some options for the text editor such as font size seting would be a welcome addition. Adding an integrated image viewer would be great too seeing as the gallery app is dropped since lollipop.

nexus 7 slimkat 9 (android 4.4.4) using f-droid buil of cabinet beta 1.9.0.8

**Comment by afollestad** [comment]
Fixed
