### ISSUE TITLE
Re-implement root access

### ISSUE THREAD

**Issue by afollestad** [afollestad/cabinet-issue-tracker#210]
People also report root deletion not persisting after reboot.

**Comment by plusCubed** [comment]
Oh my, I just tried another root library, [RootFW4](https://github.com/SpazeDog/rootfw), and it is so much faster than libsuperuser (as in, executing and getting a result from `ls -l` is almost instantaneous, so we can probably use that method to list files 100% of the time). 
I understand that libsuperuser is made by the same guy as SuperSU, so should we switch?

**Comment by afollestad** [comment]
If you feel like the newer library would be better, go ahead! Sounds like it'll benefit us

**Comment by afollestad** [comment]
@plusCubed I thought I should note:

The `File` class now has `chmod`, `chown`, and `getPermissions` methods. They're both currently un-implemented for `LocalFile`, `chmod` is currently used in the remodeled `DetailsDialog`.

**Comment by plusCubed** [comment]
Oh OK, thanks for reminding me. I'll be merging the commits from master to the wd-40 branch soon, so I'll implement/integrate them then.

**Comment by plusCubed** [comment]
@afollestad I think the wd-40 branch is in a good place to become the master branch now. Root access is mostly complete - if you turn off List Directory Count and go into a root directory it should list the files very quickly with all of the attributes of the files loaded as well.  There's a little problem with the List Directory option on that can cause things to be slow, but should be easy to fix.
There's still a lot of TODO's for root things to re-implement, but most of them should be quick to do with the new `runCommand` (blocking call) in the `App` class.

**Comment by afollestad** [comment]
@plusCubed awesome, sounds good. Feel free to merge whenever you feel is a good time.

**Comment by afollestad** [comment]
This is the last issue left before 1.9.6.0, other than finishing SD card support

**Comment by afollestad** [comment]
@plusCubed This is the last issue left before 1.9.6.0, other than finishing SD card support

**Comment by plusCubed** [comment]
The main functions should all be done. The only unimplemented method is chown, which I'll come back to later. The text editor root access is still broken though - I'll work on that.

**Comment by afollestad** [comment]
Gonna push an update to the beta channel

**Comment by afollestad** [comment]
Others are experiencing the `FileInfo` crashes: https://fabric.io/aidan-follestads-projects/android/apps/com.afollestad.cabinet/issues/55740aecf505b5ccf00fe231

**Comment by afollestad** [comment]
@plusCubed the above is actually pretty severe, the app crashes everytime I paste a file

**Comment by plusCubed** [comment]
@afollestad Can you try with the latest code? If a file's attributes are not readable, the `FileInfo` `readAvailable` boolean would be set to false and it wouldn't be compared in `equals()`, so if that crash happens it means somehow `readAvailable` is true when it shouldn't be.

**Comment by afollestad** [comment]
@plusCubed it appears to be working with the latest code, the length displays correctly again too.

Although paste (and selection mode while copying/moving) feels kinda laggy now.

**Comment by plusCubed** [comment]
@afollestad Huh. We can open another issue for that if it persists. I've re-added root to the text editor and added a read only mode instead of displaying an error. I'll close this issue and open other issues as they arise.
