### ISSUE TITLE
Save files to SD Card when shared from apps

### ISSUE THREAD

**Issue by brwolfgang** [afollestad/cabinet-issue-tracker#216]
Hi there!
ES File Explorer provides a way to save a file directly to the SD card via "ES Save to...." option in the share menu. It would be great if Cabinet did the same! 
Here's how it looks:
![ES Save to... example](https://cloud.githubusercontent.com/assets/3627736/7557798/cbe3f4cc-f765-11e4-9b8d-51174eaec968.png)
How does it work?
Well that' simple: I decided to share an audio file from Whatsapp to an external app and then the option to save it to the SD card presented itself. When the "ES Save to..." option is selected ES File Explorer opens and asks where the file should be saved.
I find it incredibly useful and would love to see it on Cabinet.
Have a great day =)

**Comment by afollestad** [comment]
I should note that you're not really saving it to anything, the file is just being copied. It exists in two places afterwards which actually isn't a good way to 'save' things.

**Comment by afollestad** [comment]
Done
