### ISSUE TITLE
Remember Scroll Position

### ISSUE THREAD

**Issue by CalH00** [afollestad/cabinet-issue-tracker#22]
When entering a folder and going back, the view is at the top again instead of where it was before.
Hope you understand what I mean, my English kinda sucks at times.

**Comment by afollestad** [comment]
Oh no I understand what you mean. I thought I had fixed that :o I'll have it fixed

**Comment by CalH00** [comment]
Great!

**Comment by afollestad** [comment]
Replacing with this: https://github.com/afollestad/cabinet-issue-tracker/issues/23
