### ISSUE TITLE
BUG?: Icon blurry

### ISSUE THREAD

**Issue by alexsmithfanning** [afollestad/cabinet-issue-tracker#221]
I am using the Google Now Launcher which has all icons scaled to a slightly larger size. I don't think the icon is big enough to scale correctly, so it is slightly blurry. Its not a big deal, just something I noticed. I don't even know if its fixable or not.

**Comment by afollestad** [comment]
Android icons are standardized in sizes. There's 4 different sizes for different screen sizes. I can't be an issue with the icon itself.

**Comment by alexsmithfanning** [comment]
Is it because I have a 720p screen resolution with a Pixels Per Inch of 326? Because the Google Earth icon isn't like that. But the Google Hangouts is. It it a problem with scaling on my specific screen?

**Comment by afollestad** [comment]
That's a possibility, yeah
