### ISSUE TITLE
Issues with merged code

### ISSUE THREAD

**Issue by afollestad** [afollestad/cabinet-issue-tracker#228]
@plusCubed 

1: Root access is requested in non-root directories, including internal storage folders and even plugin folders that are listing files from remote plugin services. The directory fragment is blank for about 10 seconds while waiting for SU to respond.

2: The other issue is a crash that occurs when moving between bread crumbs (by tapping them). The FileInfo strings somehow become null. This happens in a few other cases too.

```Gradle
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
            at com.afollestad.cabinet.file.FileInfo.equals(FileInfo.java:77)
            at com.afollestad.cabinet.adapters.FileAdapter.onBindViewHolder(FileAdapter.java:351)
            at com.afollestad.cabinet.adapters.FileAdapter.onBindViewHolder(FileAdapter.java:48)
```

**Comment by afollestad** [comment]
@plusCubed one more crash to add to that:

```Gradle
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
            at com.afollestad.cabinet.adapters.FileAdapter.onBindViewHolder(FileAdapter.java:362)
            at com.afollestad.cabinet.adapters.FileAdapter.onBindViewHolder(FileAdapter.java:54)
```

`fileInfo.directoryFileCount` is null at line 362 of `FileAdapter`.

**Comment by afollestad** [comment]
@plusCubed one more crash to add to that:

```Gradle
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
            at com.afollestad.cabinet.adapters.FileAdapter.onBindViewHolder(FileAdapter.java:362)
            at com.afollestad.cabinet.adapters.FileAdapter.onBindViewHolder(FileAdapter.java:54)
```

`fileInfo.directoryFileCount` is null at line 362 of `FileAdapter`.

Currently, this is preventing Cabinet from starting. Not sure if it's specific to plugin folders yet.

**Comment by afollestad** [comment]
Oh yeah, I can confirm it only happens with plugin folders. The new FileInfo stuff must not be compatible with plugin files?

**Comment by afollestad** [comment]
@plusCubed since it only happens with plugin files, do you have a server to test with? Or do you need access to mine for testing?

**Comment by plusCubed** [comment]
@afollestad Currently FileInfo is used by LocalFile to cache the results from `ls -l` and by the FileAdapter to cache the information provided by the `File` (any File) in the FileAdapter. There shouldn't be a problem, but I haven't tested plugins.

**Comment by afollestad** [comment]
Original comment updated. @plusCubed

**Comment by afollestad** [comment]
@plusCubed in addition to the two issues mentioned above, it appears the FileInfo class messes up attributes for PluginFiles, like isDirectory and length.

**Comment by afollestad** [comment]
Fixed the issue related to isDirectory being wrong in `FileInfo`, it wasn't accounting for the fact that permissions seem to be null for directories returned by SFTP.

**Comment by afollestad** [comment]
Fixed the issue related to isDirectory being wrong in `FileInfo`, it wasn't accounting for the fact that permissions seem to be null for directories returned by SFTP.

**EDIT**: nevermind there appears to be deeper issues.

**Comment by afollestad** [comment]
I think these issues are gone now.
