### ISSUE TITLE
Visual issues on Android M

### ISSUE THREAD

**Issue by afollestad** [afollestad/cabinet-issue-tracker#231]
![screenshot_20150528-204438](https://cloud.githubusercontent.com/assets/1820165/7874827/9c3f0ac2-057a-11e5-8e77-74f48920f72d.png)

**Comment by afollestad** [comment]
Google has a new lib coming that will have official components such as a FAB.

**Comment by plusCubed** [comment]
The design library has been released already. The FAB doesn't seem to support the popup menu we have right now though.

**Comment by afollestad** [comment]
Hmm. We'll just have to find the reason the FAB gets pushed to the right in that case.

**Comment by afollestad** [comment]
Fixed with new FAB lib.
