### ISSUE TITLE
Use new support design library's widgets

### ISSUE THREAD

**Issue by plusCubed** [afollestad/cabinet-issue-tracker#232]
https://developer.android.com/tools/support-library/index.html

`NavigationView`: navigation drawer
`FloatingActionButton`: Unfortunately doesn't have menu right now (I don't think), but we should keep an eye out for that.
`Snackbar`: Perhaps we can use this for error messages or just to replace the `Toast`s
`AppBarLayout`: Responds to scrolling (like how we already have implemented)

**Comment by afollestad** [comment]
We can't use NavigationView, our nav drawer logic is far too complex to use MenuItems. Especially with the new plugin account management stuff: NavigationView can't expand items or handle long presses.

I'm working on `SnackBar` and `AppBarLayout` right now, though.

**Comment by afollestad** [comment]
Something I might do is allow users to undo deletion rather than displaying a confirm dialog.

**Comment by afollestad** [comment]
We can't use AppBarLayout either, it needs a specific layout structure that I don't think will work with our current setup.

**Comment by afollestad** [comment]
SnackBar doesn't push the FAB up because we're not using the Design Lib FAB component. It's possible, but it requires custom `CoordinatorLayout.Behavior` to be defined.

So for now, we're not using anything from this lib in Cabinet.
