### ISSUE TITLE
Dropbox support

### ISSUE THREAD

**Issue by flodt** [afollestad/cabinet-issue-tracker#234]

**Comment by afollestad** [comment]
Haven't been keeping up with news about the plugin framework?

**Comment by flodt** [comment]
Nope, haven't. Sounds promising. 
Cheers
---
Florian Schmidt
flo@schmidt-allgaeu.de
On Jun 1, 2015 11:47 PM, Aidan Follestad <notifications@github.com> wrote:Haven't been keeping up with news about the plugin framework?
