### ISSUE TITLE
SFTP plugin not connecting to server

### ISSUE THREAD

**Issue by AndreasSchantl** [afollestad/cabinet-issue-tracker#240]
When I am trying to connect to my web server it will loop after I have pressed 'Test connection'. It won't show up any directories and will only show the load screen...

**Comment by afollestad** [comment]
Loop? Like it never times out?

Keep in mind this is SFTP, not FTP.

**Comment by afollestad** [comment]
I'm gonna assume this was an issue of trying to connect to a server that doesn't use SFTP or something.
