### ISSUE TITLE
.mkv files not recognised as video files

### ISSUE THREAD

**Issue by elfez** [afollestad/cabinet-issue-tracker#244]
If I try to open a .mkv file in Cabinet it seems to assume it is a generic (possibly text?) file and tries to open it in a text viewer. 

Renaming an .mkv file to .avi and gets around this. Also, the same .mkv file is handled correctly in other file managers (for instance Ghost Commander). Using "open as" works as well.

**Comment by afollestad** [comment]
Let me know if this isn't fixed by the next update
