### ISSUE TITLE
List View Overflow Button Issue

### ISSUE THREAD

**Issue by Beta1440** [afollestad/cabinet-issue-tracker#246]
The overflow button for the topmost file or folder in a listview often cannot be pressed. All the others appear to work fine.

**Comment by afollestad** [comment]
I'm guessing it's because you're try to press it before the fast scroller hides itself

**Comment by afollestad** [comment]
If you're in the beta channel, not Google Play version, that is.

**Comment by plusCubed** [comment]
I've changed the fast scroller activation width to 24dp so it no longer covers the overflow button. This does violate the guidelines, but I think it should be fine.
