### ISSUE TITLE
Settings checkmark color

### ISSUE THREAD

**Issue by flodt** [afollestad/cabinet-issue-tracker#254]
When changed in settings, the check mark doesn't have the accent color, but turns grey.

**Comment by afollestad** [comment]
I'm assuming you're using the Google Play version?

**Comment by afollestad** [comment]
![screenshot_20150620-192803](https://cloud.githubusercontent.com/assets/1820165/8269834/842a4cde-1782-11e5-9cb4-188caba93c3d.png)

**Comment by flodt** [comment]
Yes, I am.

**Comment by afollestad** [comment]
This isn't an issue in the beta channel version that's been under development over thrle last few months
