### ISSUE TITLE
Cut off FAB in Android M

### ISSUE THREAD

**Issue by babalonius508** [afollestad/cabinet-issue-tracker#258]
![screenshot_20150705-005602](https://cloud.githubusercontent.com/assets/13183336/8510504/a256c05a-22b0-11e5-9481-b90c8e52813e.png)

**Comment by hichem1992** [comment]
Plz add an app manager to buckup & uninstall apps & move to system app

**Comment by plusCubed** [comment]
Already fixed in latest code.
