### ISSUE TITLE
Can't view root

### ISSUE THREAD

**Issue by Juanscv** [afollestad/cabinet-issue-tracker#26]
After granting root access to Cabinet, all i get is this:

![](https://s3.amazonaws.com/pushbullet-uploads/udcnC-bJSrCvjM0xS8fb85B8MBbAAzduYhxkxV/Screenshot_2015-02-12-15-54-38.png)

I'm using Hazy ROM and it also occurred to me with another ROM (Resurrection Remix, i think).

**Comment by afollestad** [comment]
This is a bug from the old version.

We've been working on root functions all day. https://github.com/afollestad/cabinet-issue-tracker/issues/5

**Comment by Juanscv** [comment]
So there's a new version coming or a new one out already? Because i downloaded it like an hour ago.

**Comment by afollestad** [comment]
It'll be coming later today. It's everything implemented yesterday and today, which makes a changelog of around 34 things. I'll post on Google+ once it's ready.

**Comment by afollestad** [comment]
@Juanscv just as a future tip, if you look at "Closed" issues here, you can see what's already been reported and fixed :)
