### ISSUE TITLE
FAB cutoff on Nexus 5

### ISSUE THREAD

**Issue by nighthawk37** [afollestad/cabinet-issue-tracker#268]
FAB cutoff on Nexus 5 using Android M. Cabinet version 1.9.4.0 #2

**Comment by plusCubed** [comment]
Already fixed in latest code

**Comment by afollestad** [comment]
Look at closed issues before opening a new one. This is like the 4th or 5th duplicate of this issue.

**Comment by nighthawk37** [comment]
Thank you pluscubed. I did look at the closed issues before posting, none mentioned the N5 and I thought I had the latest build which still had the issue. So now to my understanding fixed in the latest code does not mean it's fixed in the latest released build?

**Comment by afollestad** [comment]
@nighthawk37 yeah, we haven't pushed an update for quite a while now. The issue is fixed in our unpublished code base.
