### ISSUE TITLE
Remember last scroll position

### ISSUE THREAD

**Issue by RamiDebab** [afollestad/cabinet-issue-tracker#27]
Suggestion : Make Cabinet remember the position of the list after performing an action(delete for example) or after accessing a folder.
Example : Imagine that i have 50 folders, i start scrolling until the 30th, i open it and then when i go back the list goes back to the number 1 so i have to scroll again, is it possible to make it remember the last folder i stopped scrolling on. it would be nice since there is already an option to go up :)

**Comment by afollestad** [comment]
Please look through closed issues before reporting new ones. https://github.com/afollestad/cabinet-issue-tracker/issues/22
