### ISSUE TITLE
In the new version 1.9.7.0 is impossible move/copy files 

### ISSUE THREAD

**Issue by luistoluca** [afollestad/cabinet-issue-tracker#272]
In the new version I can not move or copy files

**Comment by MrJSeddon** [comment]
it crashes for me as well :(

**Comment by plusCubed** [comment]
@luistoluca @MrJSeddon Can you clarify under which scenario this occurs and that this isn't another bug listed in the issues list?

**Comment by MrJSeddon** [comment]
After playing again I can't seem to repeat this bug only when copying or moving to an SD it crashes, would this be due to my LG G3 being on 5.0 and not 5.0.2+ ?

**Comment by victorz** [comment]
I can't seem to move files either. I select some files, use the context menu at the top right and select move, but nothing really happens after that. I can't seem to paste the files anywhere.

**Comment by MayuraDeSilva** [comment]
I'm experiencing the same issue. Cannot copy / move files eventhough I could select Copy / Move options. No way to paste once I've got to the desired location.

**Comment by luistoluca** [comment]
we have to push the button back in Softkeys, not use the top menu

**Comment by victorz** [comment]
I see. Kind of confusing and inconsistent that moving up a directory using the app's controls would cancel the selection and move operation, but softkey back button does not.

**Comment by afollestad** [comment]
@victorz @luistoluca @MayuraDeSilva @MrJSeddon let me know if the version live on Google Play resolves the issue.

https://play.google.com/store/apps/details?id=com.afollestad.cabinet

**Comment by afollestad** [comment]
One more will be available shortly for Android 6.0 compatibility.

**Comment by luistoluca** [comment]
@afollestad not, the new version on Play Store have the same problem, the top menu not works

**Comment by MayuraDeSilva** [comment]
Thanks for update. Now it display the paste button as I navigate through directories, but disappears upon tapping UP button.

**Comment by afollestad** [comment]
That was another issue that's been resolved, it will be in a future release

On Tue, Aug 25, 2015, 11:02 PM Mayura <notifications@github.com> wrote:

> Thanks for update. Now it display the paste button as I navigate through
> directories, but disappears upon tapping UP button.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afollestad/cabinet-issue-tracker/issues/272#issuecomment-134819300>
> .
>
-- 

Best regards,

Aidan Follestad,
http://aidanfollestad.com
651-528-1662

**Comment by MayuraDeSilva** [comment]
Cool! Lookin' forward to it :)
