### ISSUE TITLE
Pressing 'up' deselects file while moving/copying

### ISSUE THREAD

**Issue by noahwass** [afollestad/cabinet-issue-tracker#274]
I'm using Cabinet on the Android M preview 2 and cannot move files from one folder on my Nexus 5 to another folder. I can select a file to move, select the Move action, but then the action goes away and the file is no longer selected.

Cabinet version:1.9.7.0.

**Comment by noahwass** [comment]
So, to clarify: the old method of moving files didn't work. I was able to use the back button to return to the root directory while the file was still selected. Previously, I was able to use the up arrow in the upper right hand corner to navigate back to the root directory.

**Comment by plusCubed** [comment]
Fixed.

**Comment by noahwass** [comment]
Thanks, guys!
