### ISSUE TITLE
Hamburger to Back Arrow Animation when tapping 'Search'

### ISSUE THREAD

**Issue by CalH00** [afollestad/cabinet-issue-tracker#28]
Does it comply to the material design guidelines if the hamburger icon turns into an arrow animatedly when you tap on the search button?
It'd certainly look nice.

**Comment by afollestad** [comment]
Unfortunately this would require too much modification. You can't do this with Android or AppCompat's SearchView, so you basically have to recreate the system Android uses to display a search UI within the toolbar to do this.
