### ISSUE TITLE
Add LAN or SMB browsing

### ISSUE THREAD

**Issue by Nilpo** [afollestad/cabinet-issue-tracker#285]
Can you add LAN or SMB browsing so that shared folders can be browsed using Android's built-in VPN?  Is there a code repository to contribute to?

**Comment by afollestad** [comment]
Someone else can when the plugin framework is fully rolled out.

**Comment by Prajjwal** [comment]
> Someone else can when the plugin framework is fully rolled out.

What's the ETA on that?
