### ISSUE TITLE
Superuser not available error when moving between root/internal storage

### ISSUE THREAD

**Issue by csamolot** [afollestad/cabinet-issue-tracker#287]
When moving between root and any internal storage directory after allowing root access I get a superuser not available file and in order for me to navigate to directory I have to go to root and navigate down to the directory instead of being able to use short cut path in side menu. Running cm 11 kitkat.

**Comment by plusCubed** [comment]
Should be fixed internally. This fix will come out in the next update. Let us know by re-opening this issue if this comes up again.

**Comment by JohnWestUA** [comment]
I have this error when moving, renaming or copying files in internal storage.
Nexus 5 4.4.4. (CM11). The latest version of Cabinet.

**Comment by homanwang** [comment]
I have this error when moving, renaming or copying files as well.
Galaxy Note 2 N7100 4.4.2 Original Sys. The latest version of Cabinet.
