### ISSUE TITLE
FAB: Icons aren't visible if the accent color is white

### ISSUE THREAD

**Issue by ianbrunelli** [afollestad/cabinet-issue-tracker#289]
See screenshot:

![screenshot_2015-08-25-11-31-42](https://cloud.githubusercontent.com/assets/5755892/9469444/77bfdcba-4b1d-11e5-9cbd-faf7949c8f08.png)

**Comment by alorma** [comment]
I assign it to myself, if @afollestad is ok with it.

**Comment by alorma** [comment]
Fixed
