### ISSUE TITLE
Show free/used space somewhere

### ISSUE THREAD

**Issue by afollestad** [afollestad/cabinet-issue-tracker#29]
Not sure how this would be done efficiently though, since files are constant changed and scanning the entire file system is pretty intensive Big-Oh wise.

**Comment by CalH00** [comment]
Maybe in the side bar, below 'Root' and 'Internal Storage'?
Yes, that's straight from Solid Explorer.

**Comment by afollestad** [comment]
Haha, yeah that could work. Definitely for a future release though.

**Comment by arkon** [comment]
Can probably use [StatFs](http://developer.android.com/reference/android/os/StatFs.html).

**Comment by afollestad** [comment]
Done
