### ISSUE TITLE
File renaming is broken

### ISSUE THREAD

**Issue by anowlcalledjosh** [afollestad/cabinet-issue-tracker#297]
If you have two files called 'foo' and 'bar', renaming 'foo' to 'bar ' will actually rename it to 'bar (1)'. This is acceptable.

However, if you have a file 'quux', open the renaming dialog box and press OK, it gets renamed to 'quux (1)'.

In addition, if you have a file called 'quux' and rename it to 'QuuX', it will get renamed to 'QuuX (1)'.

Hilarity ensues when you continue to open/press OK on the renaming dialog and change the case of the filename (e.g. 'qUUx (1) (1) (1)').

**Comment by plusCubed** [comment]
Root cause: #290

**Comment by plusCubed** [comment]
Fixed.
