### ISSUE TITLE
if the primary color is white, the font is not changed to black, which is why it all drained.

### ISSUE THREAD

**Issue by ventura16** [afollestad/cabinet-issue-tracker#301]
If the primary color is white, the font is not changed to black, which is it all drained.

**Comment by ventura16** [comment]
Please, sorry for my bad English

**Comment by plusCubed** [comment]
Assuming this is your post (images of issue): https://plus.google.com/106511550145060745466/posts/JBwFGJnw2ZM

**Comment by plusCubed** [comment]
Actually I don't think white is an option anymore internally. Let us know if you want to have white as an option, but for now I'll close this issue.
