### ISSUE TITLE
Let user chose application when touching a file

### ISSUE THREAD

**Issue by Guema** [afollestad/cabinet-issue-tracker#303]
Cabinet, at this time, just open itself supported file formats, but could it let user the choise ?
for exemple, let user open pdf file in google pdfviewer
or photos in google photos.

i think there is a built-in android library that already do it.
thanks

**Comment by afollestad** [comment]
It opens with the default, whatever you choose to open the same file type with in the past. You can clear defaults for the destination app to show the app picker again. 

There's also an "Open with..." option in the app.

**Comment by Guema** [comment]
Hum, ok, my bad so...
