### ISSUE TITLE
Cabinet image viewer don't read annimated gif correctly

### ISSUE THREAD

**Issue by Guema** [afollestad/cabinet-issue-tracker#304]
animated thumnails are working, but openning a gif disable the animation.

**Comment by afollestad** [comment]
Cabinet doesn't have an image viewer. It opens with with image viewers you have installed. 

Have you used Android before?

**Comment by Guema** [comment]
hum, ok, i think this bug is specific to my phone, then i am not able to know in wha app the gif is open
google photos supports gif, so i don't think it is this one

**Comment by Guema** [comment]
that's strange, i reseted apps affinities, and .gif and other images are style launched in a secret app that don't support animated ones.

**Comment by Guema** [comment]
To answer to you, im not android newbie. I verified some things and it seems that animated gif are really un readable when openned by cabinet. Did you tryied to reproduce ?
Animated gif works when opened in google photos directly, but not when openned by cabinet.

**Comment by arkon** [comment]
Cabinet definitely doesn't have a built-in image viewer -- check the package browser in dev tools.

**Comment by Guema** [comment]
Yeah, that was what i supposed firstly... But in fact i have a bug reading annimated .gif using cabinet.

Cabinet is used as explorer and when openning photo, it switchs to google photo and animation is disabled. Everything works fine when i use google photo to explore images.

**Comment by Guema** [comment]
Maybe ill try with other explorer to see if this problem is specific to google photo or specific to cabinet

**Comment by afollestad** [comment]
All that Cabinet does it pass the file path to another app.

Cabinet doesn't do anything to display photos.

**Comment by Guema** [comment]
Yup, sorry for this bug report 
i discovered this bug was relative to Google Photos.
other file manager reproduce it on any android device.
Thanks for your attention and sorry for the inconvenience
