### ISSUE TITLE
SFTP - Where is it?

### ISSUE THREAD

**Issue by olejon** [afollestad/cabinet-issue-tracker#308]
I'm running Android 6 on my Nexus 5 and there is no longer an option to connect to remote servers. Has it been removed, and if so, why?

**Comment by afollestad** [comment]
If was removed over a year ago. There's a plugin, but it's been in beta for a while.

https://plus.google.com/communities/110440751142118056139

https://play.google.com/apps/testing/com.afollestad.cabinetsftp

**Comment by olejon** [comment]
I have installed the plugin and have the latest Cabinet Beta, and the plugin says `Connection successful` when trying it, but when connecting, it says `ClassNotFoundException when unmarshalling: com.afollestad.cabinet.plugins.PluginFile`

Nexus 5, running Android 6 (*may that be the problem?*)
