### ISSUE TITLE
Erro ao copiar arquivo

### ISSUE THREAD

**Issue by JrFernando** [afollestad/cabinet-issue-tracker#309]
Não consigo copiar arquivos do celular para o pen drive, fui copiar a pasta DCIM para o pen drive, apenas a pasta foi copiadas o arquivos q estavam contidos não foram copiados

**Comment by afollestad** [comment]
Sorry, no one here speak Spanish.

**Comment by afollestad** [comment]
External storage support is not done, though.

https://github.com/afollestad/cabinet-issue-tracker/issues/211
