### ISSUE TITLE
Folder Switching not working properly

### ISSUE THREAD

**Issue by CalH00** [afollestad/cabinet-issue-tracker#31]
When I open a folder and go back, I can't open that exact folder again right away - the active breadcrumb changes, but the contents of the folder I switch to aren't displayed, it stays in the previous folder.
Can you reproduce this by doing that: Open a folder, tap 'Back', tap the same folder again (not the breadcrumb).
?

**Comment by afollestad** [comment]
Oh yeah, good find.

I reproduced it by tapping a folder, tapping the first bread crumb, and tapping the folder again. I'll try to get another fix update out today.

**Comment by afollestad** [comment]
Fixed

**Comment by CalH00** [comment]
Nice :-).
