### ISSUE TITLE
Failed to Rename/move this file:Root acces denied

### ISSUE THREAD

**Issue by sysdroid98** [afollestad/cabinet-issue-tracker#311]
Since the last version, rename or move a file, I get this error, this happens with files in the internal memory and SD card, reinstall the application and got the same error

Motorola XT1040
Android KitKat 4.4.4 Build KBX21.14-L1.56 Room Stock
Cabinet 1.9.8.1
No Root
![screenshot 08-21am oct 23 2015](https://cloud.githubusercontent.com/assets/15264562/10693971/43e15168-7961-11e5-964d-5521875b775b.png)

**Comment by sysdroid98** [comment]
Yesterday, i update my phone to Android 5.1, and this issue it's solved.

**Comment by andry888** [comment]
Actually, this issue still persists for Android under 5.0
