### ISSUE TITLE
Extreme lag when using external storage (on Marshmallow)

### ISSUE THREAD

**Issue by XorgMC** [afollestad/cabinet-issue-tracker#316]
First, this is the first manager which can read/write on sdcards on Marshmallow. But it lags extremely compared to use on internal storage

Can this be fixed or is this because of the access method?

**Comment by XorgMC** [comment]
Here you can see it on my Xperia Z3: https://youtu.be/EyIeHJ2--s0

First internal storage (smooth), then external SD (lag)

**Comment by afollestad** [comment]
https://github.com/afollestad/cabinet-issue-tracker/issues/211
