### ISSUE TITLE
Cabinet connects to the Internet at first run

### ISSUE THREAD

**Issue by okungnyo** [afollestad/cabinet-issue-tracker#319]
I just checked my phone's Data usage, and apparently Cabinet (which I just fresh installed) has used 20 to 100 KB of data.

Why?

There is no reason for a local file manager to be transmitting data over the Internet.

I hope it's not phoning home with user data..

Edit: 20 to 100 KB

**Comment by HeinrichReimer** [comment]
It's probably only statistics

**Comment by plusCubed** [comment]
Crashlytics.
