### ISSUE TITLE
Ticking or unticking 'Show Current Path' doesn't immediately update the title.

### ISSUE THREAD

**Issue by CalH00** [afollestad/cabinet-issue-tracker#32]
When I tap the overflow button and untick / tick 'Show Current Path', the title won't immediately change from 'Cabinet' to the current folder name / vice versa.

**Comment by afollestad** [comment]
Another good find

**Comment by CalH00** [comment]
I hope I can figure out what that third bug was again soon enough.

**Comment by afollestad** [comment]
Fixed.

And yeah let me know, I'll have to get another update out whenever you do

**Comment by CalH00** [comment]
I think it was just something I didn't quite understand at first and not a bug. Oops.
Gonna look through other parts of the app though and see if I can find anything.

**Comment by afollestad** [comment]
Haha okay, sounds good

**Comment by CalH00** [comment]
Nope. The other bug was the one with the scroll position from earlier. Guess you gotta look into that one again.
