### ISSUE TITLE
Hide/remove the floating " + " 

### ISSUE THREAD

**Issue by peterj71** [afollestad/cabinet-issue-tracker#325]
I never create Files in Explorer (I only ever create them inside apps, e.g. I'd go to Word to create a new Word doc, not Explorer) and I very rarely create Folders, so the floating " + " is an unnecessary nuisance for me. An option to hide this floating button and instead have the add folder/file accessible from the " ... " menu would be better and cleaner.

**Comment by afollestad** [comment]
Removing the FAB isn't gonna happen

**Comment by okungnyo** [comment]
He/she didn't say you had to remove it, there's also the possibility of having an option in Settings.

**Comment by afollestad** [comment]
I'd like to avoid too many settings, and moving large functions like that around will bulk up the code quite a bit.

**Comment by okungnyo** [comment]
OK then.
