### ISSUE TITLE
Show folder name instead of "Cabinet" in app bar

### ISSUE THREAD

**Issue by peterj71** [afollestad/cabinet-issue-tracker#326]
In the app bar above the file and folder count it always says "Cabinet" in big letters. This is not intuitive when the file and folder count are always changing depending on current folder, the name of which is in small caps underneath. It would make more sense to me if the current folder name were in big letters at the top of the app bar (and in the actual upper/lower/mixed case of the actual folder name).

**Comment by afollestad** [comment]
It does so if you turn off the breadcrumbs (bar that shows the full path).
