### ISSUE TITLE
Nuevas características

### ISSUE THREAD

**Issue by GustavoWiesner** [afollestad/cabinet-issue-tracker#327]
Hola chicos, como están?
Soy un exiliado de ES Explorador de Archivos, luego de los cambios realizado por Estrongs y de barajar alternativas, elegí a Cabinet como mi explorador de archivos.
Lo que me gusto de está aplicación sin duda alguna es su diseño, personalmente el Material Design me atrae demasiado y el mismo debería ser un estándar en todas las aplicaciones de Android.
La cuestión es que la aplicación esta "verde" por el momento, con algunas actualizaciones podría mejorar bastante la experiencia de usuario (no exagero).
Las características que planteó son:
• Descomprimir archivos .rar, .img, .iso 
• Compartir archivos mediante conexión LAN (Wi-Fi/Bluetooth).
• Manifiesto de instalación y comparación con una aplicación instalada (http://i.imgbox.com/JlTn9rF6.png).
• Reproductor (y no previsualización) de audio y vídeo en Material Design.
• Más optimización y menos peso.
• Más Material Design.
Saludos y un abrazo a los desarrolladores de esta increíble aplicación 😁

**Comment by afollestad** [comment]
Sorry, no one here speaks Spanish

**Comment by GustavoWiesner** [comment]
Too bad, he invited him to use an online translator or Spanish-English dictionary. Regards.

**Comment by afollestad** [comment]
I am the developer, we use crowd source translations.

Online translators aren't the most accurate. Individual feature requests belong in their own issues, rather than a list in one issue.
