### ISSUE TITLE
"Up" doesn't navigate properly

### ISSUE THREAD

**Issue by arkon** [afollestad/cabinet-issue-tracker#33]
Tapping up in the toolbar reflects going to the parent directory in the breadcrumbs, but doesn't actually show the parent directory's contents in the RecyclerView.

Tapping on the "Internal Storage" breadcrumb after tapping up also fails to do anything.

**Comment by afollestad** [comment]
Hmm, it seems to be working for me.

Tapping up from internal storage leads to "/storage/emulated" which shows "Root" > "Storage" > "Emulated" breadcrumbs.

**Comment by arkon** [comment]
I think it might actually be an off-by-one error. I just navigated 4 directories deep, and it seems to be showing things one level off (will keep investigating).

**Comment by arkon** [comment]
Here's a video demonstrating what I was talking about: https://www.youtube.com/watch?v=uT-yI5CIuF0

**Comment by afollestad** [comment]
Oh wow, that's very weird

**Comment by arkon** [comment]
The content is shown properly upon tapping up in the latest unreleased code, but using the breadcrumbs after tapping up results in some unexpected results (shows wrong directory contents).

**Comment by arkon** [comment]
I _think_ it has something to do with `onCrumbSelection` in `NetworkedActivity.java` and how it pops from the fragment manager backstack.

**Comment by afollestad** [comment]
@arkon I pushed a few more things. I'm going to bed now though.
