### ISSUE TITLE
wrong icon on items selection 

### ISSUE THREAD

**Issue by enricocid** [afollestad/cabinet-issue-tracker#331]
![screenshot_20151218-231932](https://cloud.githubusercontent.com/assets/7274841/11908620/07630084-a5de-11e5-8d0c-d8e3699fa127.png)

![screenshot_20151218-232956](https://cloud.githubusercontent.com/assets/7274841/11908759/5b16cd40-a5df-11e5-9c7f-8160a7c09c78.png)

how to reproduce the issue:

select an item by long click ---> Details (or the other buttons on that popup menu) ---> click on X to cancel section 

and You get the results in screenshot :)

Nexus 5 , Android 6.0.1 Stock

**Comment by afollestad** [comment]
https://github.com/afollestad/cabinet-issue-tracker/issues/322
