### ISSUE TITLE
Re-navigating to a directory fails

### ISSUE THREAD

**Issue by arkon** [afollestad/cabinet-issue-tracker#34]
If you enter a directory, go back, then try to go back to that same directory, it doesn't actually do so (but is reflected properly in the breadcrumbs).

**Comment by afollestad** [comment]
That's been fixed: https://github.com/afollestad/cabinet-issue-tracker/issues/31

**Comment by arkon** [comment]
@afollestad Really? It's happening in v1.9.2.0.1

**Comment by afollestad** [comment]
Yeah, I haven't pushed an update for it yet, it was just reported but already fixed

**Comment by arkon** [comment]
Aha, got it. :smiley:

**Comment by afollestad** [comment]
Just added you to the private repo if you wanna test it :)

**Comment by arkon** [comment]
Seems like it's fixed. :+1:
