### ISSUE TITLE
Laggy ui when browsing external storage

### ISSUE THREAD

**Issue by noobpremium** [afollestad/cabinet-issue-tracker#343]
Device-Xiaomi redmi 2 running unofficial (almost) stable cm13
Today I installed this app. Its beautiful.
Just one issue. UI becomes laggy when browsing ext sdcard. No issues with internal storage and root directories.
Thank you for your work. Playstore needed a explorer like this. Simple clean and material :p

**Comment by afollestad** [comment]
https://github.com/afollestad/cabinet-issue-tracker/issues/211
