### ISSUE TITLE
Drawer shortcuts sometimes don't work

### ISSUE THREAD

**Issue by arkon** [afollestad/cabinet-issue-tracker#37]
Example: go to Pictures, dive into some subdirectories, then try using the Pictures shortcut again.

**Comment by afollestad** [comment]
Are you using 1.9.0.2? This is related to that first issue you reported (which was fixed), I believe. Same mechanism as tapping the same folder again.

**Comment by afollestad** [comment]
Yeah I believe this was related to https://github.com/afollestad/cabinet-issue-tracker/issues/31

**Comment by arkon** [comment]
Awks, sorry. I'm still importing the project into Android Studio (since I had to reboot into Linux to do it too).

**Comment by afollestad** [comment]
It's okay, haha

**Comment by arkon** [comment]
Yup, this is fixed.

**Comment by afollestad** [comment]
Awesome
