### ISSUE TITLE
Breadcrumbs always jumps to right

### ISSUE THREAD

**Issue by plusCubed** [afollestad/cabinet-issue-tracker#43]
Even when, say, pressing root.

**Comment by afollestad** [comment]
That's done with `addCrumb()` is invoked from `BreadCrumbLayout`.

**Comment by afollestad** [comment]
I think scrolling to the active crumb would be a good way to handle this, but there's no method for that in `HorizontalScrollView`

**Comment by afollestad** [comment]
Oh wait, maybe there is: http://stackoverflow.com/a/22867159/309644

`getLeft()` or `getRight()` (based on `Utils.isRTL()`) can be used for the x coordinate when smooth scrolling. Some padding, such as 16dp, should probably be added to that scroll space too. @plusCubed

**Comment by plusCubed** [comment]
@afollestad Ah right, thanks for reminding me about RTL support, completely forgot.

**Comment by afollestad** [comment]
Haha no problem

**Comment by afollestad** [comment]
Decided to just to it now since it's a pretty easy fix, it's in the latest commit but I gotta test it a bit more
