### ISSUE TITLE
Fix root directory listing speed, and other root functions

### ISSUE THREAD

**Issue by afollestad** [afollestad/cabinet-issue-tracker#5]
Listing root files is very, very slow compared to apps like Solid Explorer Alpha.

Also, a user was unable to move a file to system/media with root access. Other users report not being able to edit files such as build.prop. Other root functions, like permission modification, should be verified.

Basically, the way root directories are read needs to be changed. And it needs to be verified that root access modifications are actually applied.

**Comment by afollestad** [comment]
@plusCubed it seems one of the main causes is the way ls output is parsed, but as far as I know there's no other way for us to list files with root permissions.

**Comment by plusCubed** [comment]
@afollestad Hmmm... what instead of `ls` with `-l` , we lazy load the permissions and details when we open the properties window (get those details later)? Perhaps that'll help with speed?

**Comment by afollestad** [comment]
@plusCubed well, the `-l` parameter also gives us other information, e.g. the length of a file, if no length is specified than it's a directory (Linux treats directories as files with no specific length).

**Comment by plusCubed** [comment]
@afollestad We can get that information by making a java File object using the path. I think I read somewhere that we can always create a File with the entire path, regardless of folder permissions, so /data/app should work. Let me check.

**Comment by afollestad** [comment]
@plusCubed oh okay, so they just don't show up with File.listFiles(). Hopefully that's the case.

**Comment by afollestad** [comment]
Huh, looks like the File class does work with root files. So we can use plain "ls" for listing.

I'm gonna try it now.

**Comment by afollestad** [comment]
It's so much faster! I was able to remove the RootFile class altogether too

**Comment by plusCubed** [comment]
Hmmm... I'm thinking we can also further improve speed by resorting to using `ls` only when it gives an `SecurityException` in `File.listFiles()`. Is that viable?

**Comment by afollestad** [comment]
I'm not sure that exception is thrown, it seems like it just returns nothing. Maybe I just didn't notice any exceptions. If that's the case, that would be great.

**Comment by plusCubed** [comment]
@afollestad If it isn't thrown we can resort to `ls` to double check if it returns nothing then. I'm in class so I can't test it right now.

**Comment by plusCubed** [comment]
Working on it now

**Comment by afollestad** [comment]
Awesome.

Once this is done and https://github.com/afollestad/cabinet-issue-tracker/issues/23 is done, and update will go out. I'm almost done with 23.
