### ISSUE TITLE
Better Zip Unpacking

### ISSUE THREAD

**Issue by CalH00** [afollestad/cabinet-issue-tracker#51]
When I unpack a zip file, I don't really want to extract them into the folder I'm currently in, especially not if it's in the 'Downloads' folder.
So I'd love it if it worked like this:
1. Tap the three dots on a zip file.
2. Tap 'Unpack To...'.
3. Navigat﻿e to the folder you want to extract it to.
4. Tap a FAB that suggests pasting or extracting.
5. Done.

**Comment by afollestad** [comment]
This will come with the archive viewer so I'm closing this

**Comment by CalH00** [comment]
K.
