### ISSUE TITLE
Bread crumb issues with internal storage

### ISSUE THREAD

**Issue by afollestad** [afollestad/cabinet-issue-tracker#54]
If you navigate from /storage/emulated (which shows up as "Root" > "Storage" > "Emulated" in the bread crumbs), and then tap "0", it shows "Root" > "Internal Storage" instead of just "Internal Storage".

Once "Root" > "Internal Storage" shows up, tapping "Root" goes back to /storage/emulated rather than /.

**Comment by plusCubed** [comment]
Well, there's the `sdcard` symlink in root that goes to the internal storage. Related perhaps?

**Comment by afollestad** [comment]
Not quite, it's related to the logic in `setActiveOrAdd` which isn't perfect yet as it appears

**Comment by arkon** [comment]
I think this started happening after some commits pertaining to the breadcrumb logic last night.

**Comment by afollestad** [comment]
They did, the logic fixed some stuff such as saving scroll positions though

**Comment by afollestad** [comment]
Before last night, the back stack was being rebuilt every time you change directories, so fragments didn't keep their instance states. 

I added an extra measure to that by storing saved scroll positions in the crumbs so they're saved when you go forward in the stack where a fragment doesn't exist yet.

**Comment by afollestad** [comment]
This is definitely the highest priority bug right now

**Comment by arkon** [comment]
Confirming that the described scenario does indeed happen. Technically, going back to /storage/emulated is correct (in terms of how you got there via symlinks), but I guess that's not the expected functionality.

**Comment by afollestad** [comment]
It's correct when you go back, the issue is when you go forward again. There's other various scenarios where the path gets messed up, too.

**Comment by afollestad** [comment]
This should be fixed. Let me know if you guys notice any weird navigation issues with the bread crumbs.

Basically, this will correct compression "/storage/emulated/0" to "Internal Storage" even if you navigate to it from the root directory.
