### ISSUE TITLE
When show hidden files is enabled, some folders appear blue when they shouldn't be

### ISSUE THREAD

**Issue by afollestad** [afollestad/cabinet-issue-tracker#57]
I haven't been able to reproduce this, but I've gotten a few reports

**Comment by afollestad** [comment]
@plusCubed @arkon can either of you reproduce this issue?

**Comment by arkon** [comment]
I'm assuming you mean it takes the appearance of a hidden folder, since mine aren't blue normally. 

I haven't ever noticed this though.

**Comment by plusCubed** [comment]
@afollestad @arkon Me neither, can't reproduce. Are the reports from one specific Android version (or something else to narrow it down)?

**Comment by afollestad** [comment]
I'm not really sure what Android version they were using. But yeah the issue is that folders are colored blue, which is the default folder icon color before the color filter gets applied to it.

**Comment by afollestad** [comment]
I'm going to class now. But once this and https://github.com/afollestad/cabinet-issue-tracker/issues/73 are fixed, we can push an update.

We should try to look for any other quirks or bugs while browsing through the app too.

**Comment by afollestad** [comment]
Do you think this was an issue with vectors before? @plusCubed

**Comment by plusCubed** [comment]
@afollestad  I think this issue existed before we added the vectors?
