### ISSUE TITLE
Dialog text fields aren't focused

### ISSUE THREAD

**Issue by arkon** [afollestad/cabinet-issue-tracker#59]
Dialog boxes such as "New folder" or "Rename" should have focused text fields upon opening them.

**Comment by afollestad** [comment]
Fixed

**Comment by arkon** [comment]
It seems like the soft keyboard is opening and immediately closing for me. Is this happening for anyone else?

**Comment by afollestad** [comment]
It was but I fixed it late last night

**Comment by arkon** [comment]
Weird, I've pulled the recent changes though.
