### ISSUE TITLE
Indicate symlinks and where they point to

### ISSUE THREAD

**Issue by plusCubed** [afollestad/cabinet-issue-tracker#65]

**Comment by arkon** [comment]
Do you mean explicitly indicating that something is a symlink as opposed to a hard link?

**Comment by plusCubed** [comment]
@arkon Yes.

**Comment by plusCubed** [comment]
@arkon Also where it points to.

**Comment by plusCubed** [comment]
Added initial support to the listing of symlinks. It's not very pretty, but it works - @afollestad  you can try it out in the root directory (/d, /etc, /sdcard).
