### ISSUE TITLE
Keyboard stays open after input dialog closes

### ISSUE THREAD

**Issue by afollestad** [afollestad/cabinet-issue-tracker#67]

**Comment by plusCubed** [comment]
http://android-developers.blogspot.com/2012/05/using-dialogfragments.html?m=1
I'm not at a computer right now, you can use the method here.

**Comment by afollestad** [comment]
Hmm, that doesn't really work to open it. If I use the current method to open it, that method also doesn't work to close it.

**Comment by afollestad** [comment]
I slightly changed the code I had been using before and it works now
