### ISSUE TITLE
Archive viewer

### ISSUE THREAD

**Issue by afollestad** [afollestad/cabinet-issue-tracker#68]
So it can be shown as if browsing a directory. The major difference will be that it doesn't switch fragments when folders are tapped, it will just reload adapter contents since it has to keep track of the ZIP file entries without reloading the fragment everytime.

**Comment by afollestad** [comment]
I need to solve when bread crumbs don't get added for subfolders, and I need to solve why the active crumb is not set when receiving the ACTION_VIEW intent for ZIP files.

**Comment by afollestad** [comment]
I need to solve why bread crumbs don't get added for subfolders. They just replace the ZIP's bread crumb.

E.g. MyFile.zip turns into "MyZipFolder", which turns into "MyZipFolder/SubSubFolder" rather than "MyFile.zip" > "MyZipFolder" > "SubSubFolder".

**Comment by afollestad** [comment]
Bread crumbs now work.

Now, files need to be extracted to temp files when opened from inside the archive viewer, and the 'Extract' action needs to extract the entire archive to a chosen location.

**Comment by afollestad** [comment]
Done, needs testing

@plusCubed @arkon

**Comment by arkon** [comment]
@afollestad Seems to function well. The up option in the toolbar isn't present though, not sure if intentional or just left out.

Going back into a relatively large ZIP shows that it's being reloaded again too, although this is semi-expected.
