### ISSUE TITLE
I was asked to grant root when copying from internal storage to another folder in internal storage?

### ISSUE THREAD

**Issue by afollestad** [afollestad/cabinet-issue-tracker#73]

**Comment by plusCubed** [comment]
Try it again with the latest code. It should have been fixed in afollestad/cabinet@46ec4d2ece1029a1f70135899e19941905e9aa45

**Comment by afollestad** [comment]
Yeah I was using the latest code when I tested it, I believe

**Comment by afollestad** [comment]
Wait, nvm, it seemed to go away all of a sudden
