### ISSUE TITLE
Root file properties issues b/c of java.io.File

### ISSUE THREAD

**Issue by plusCubed** [afollestad/cabinet-issue-tracker#75]
The Java `File` thinks the file doesn't exist (`exists()` returns false), but it does. This is due to no read permission for the "others" scope.

This causes weird issues like not being able to open it in the text editor (since it depends on the Java file) and having their file sizes as 0.

Example: Any files in /data/system/

**Comment by plusCubed** [comment]
File sizes are easy enough to fix, I'll work on that first. I'm not sure how to approach the text editor problem.

**Comment by afollestad** [comment]
This and https://github.com/afollestad/cabinet-issue-tracker/issues/57 are the last before a Google Play update

**Comment by afollestad** [comment]
This is originally one of the reasons why I had been parsing "ls -l" output for root files, btw

**Comment by afollestad** [comment]
Also, the Text Editor can attempt to read the file and close in the case of an exception rather than checking for existence with `exists()`. But that issue would still elsewhere. @plusCubed

**Comment by afollestad** [comment]
I made it so that the text editor attempts to read it rather than checking if it exists first. Although now permission denied errors are received, as if mounting isn't working. I'm gonna publish an update though.

**Comment by plusCubed** [comment]
I added a workaround for the file sizes issue, but it causes a lot of lag because it's run on the same thread.

**Comment by plusCubed** [comment]
Text editor fixed, still need to move file size/information getting to separate thread.

**Comment by afollestad** [comment]
@plusCubed I believe you implemented this stuff in the latest commits, right?

**Comment by plusCubed** [comment]
@afollestad Well, still partially. File size is fixed for these ghost files. Some other attributes like date modified still need to be implemented. I brought back `LsParser` for those attributes, just need to find a way to do it on a separate thread with the least number of `ls` commands (right now, temporarily, file size for these files is obtained by calling ls for each file).

**Comment by afollestad** [comment]
Just to log all relevant info, I believe this is related: https://plus.google.com/101876697001374390622/posts/BfBeUi7jETC

**Comment by afollestad** [comment]
Closing in favor of https://github.com/afollestad/cabinet-issue-tracker/issues/210
