### ISSUE TITLE
Another weird issue which multiple people reported 

### ISSUE THREAD

**Issue by afollestad** [afollestad/cabinet-issue-tracker#80]
This is a screenshot posted in the community:

![15 - 1](https://cloud.githubusercontent.com/assets/1820165/6242838/eb77659e-b6fb-11e4-970b-e79dcc151e74.png)

**Comment by afollestad** [comment]
The folders at the bottom are black

**Comment by afollestad** [comment]
Might be related to issue https://github.com/afollestad/cabinet-issue-tracker/issues/57

**Comment by plusCubed** [comment]
Same issue I believe, the vectors' default color is black.
