### ISSUE TITLE
Back stack gets messed up when coming back to the app after a while 

### ISSUE THREAD

**Issue by afollestad** [afollestad/cabinet-issue-tracker#81]
E.g. my back stack when leaving the app is:

"Internal Storage" > "DCIM" > "Camera"

When I come back to the app later, they're still like that. However, if I click "Internal Storage", it stays in "DCIM" as if an extra fragment back stack entry got in there.

**Comment by afollestad** [comment]
Can't reproduce again for now

**Comment by plusCubed** [comment]
With "Don't keep activities" selected in the developer options, this happens a lot more (Still not 100%, but this should help with debugging).

**Comment by afollestad** [comment]
Oh yeah, weird. Not sure why this happening.

**Comment by afollestad** [comment]
Well the first thing I noticed, is that `addArtificalBackStack()` only gets called for the last directory.

**Comment by afollestad** [comment]
I believe I found a solution

**Comment by afollestad** [comment]
Fixed!
