### ISSUE TITLE
Re-Navigation into zip-files only possible via breadcrumb

### ISSUE THREAD

**Issue by CalH00** [afollestad/cabinet-issue-tracker#82]
When opening a zip folder and going back, you can only get back into it via the breadcrumb. If you try to do it via the list entry of that zip folder, it doesn't work, but if you try to tap the breadcrumb of the previous folder, it's blank. If you open a folder inside that zip file, sometimes the view of the previous folder is fixed, sometimes it shows the contents of the zip folder.

**Comment by afollestad** [comment]
Good catch, fixed
