### ISSUE TITLE
Bad encoding for some text files

### ISSUE THREAD

**Issue by afollestad** [afollestad/cabinet-issue-tracker#9]
E.g. text encoding with what Spanish uses (must not be UTF-8?)

**Comment by plusCubed** [comment]
[ICU4J](http://site.icu-project.org/) might be useful. It has a character set detector (well, guesser).

**Comment by afollestad** [comment]
Oh yeah, good idea

**Comment by afollestad** [comment]
This is now implemented (ICU4J), but it needs to be tested
