### ISSUE TITLE
App backup feature(ability to create apk from preexisting app)

### ISSUE THREAD

**Issue by AnkitJose** [afollestad/cabinet-issue-tracker#94]
I'm really sorry for posting this thread again but I'm just saying- how does es file explorer do it then? es file explorer can create apk backups without root. I myself use the feature on a regular basis.

**Comment by AnkitJose** [comment]
FYI. The only reason I'm not fully adapting to cabinet is due to the lack of this feature. You know you sometimes wanna share a game with a friend who really wants it!

**Comment by afollestad** [comment]
You could've re-opened the other one rather than creating duplicates, this makes everything messy. 

I'm not sure how that could possibly be done, /data/app is the only place user-installed apps go. Regardless, this doesn't seem necessary to me, especially since it aids app pirating.
