### ISSUE TITLE
Issue with text editor changing file permissions on save

### ISSUE THREAD

**Issue by afollestad** [afollestad/cabinet-issue-tracker#95]
From an emailed report:

"When I edit a file in /system/etc, once the file is saved, the permissions change to 0600 when it was originally 0644. This broke some audio playback for me. No biggie but might break something more serious if it was in important file."

**Comment by plusCubed** [comment]
Should be fixed with afollestad/cabinet@83d1ae5c479dd67f2df4543146a3b7a7cc9fb169

**Comment by afollestad** [comment]
Oh yeah didn't notice that, thanks
