### ISSUE TITLE
SD card should be added or removed from nav drawer based on mounted state, bread crumbs need to be invalidated based on mount state too

### ISSUE THREAD

**Issue by afollestad** [afollestad/cabinet-issue-tracker#99]

**Comment by afollestad** [comment]
@arkon it would be helpful if you could test this

**Comment by arkon** [comment]
I unmounted the SD card, reopened the app, and it shows a "sdcard1" item in the nav drawer. Entering it opens up an empty folder (and requested root).

**Comment by arkon** [comment]
Remounting the SD card works as expected though, the app immediately shows its contents again, even without relaunching it. The nav drawer also correctly says "SD Card" again, although the breadcrumb continues to say "sdcard1" until it's renavigated to again.

**Comment by afollestad** [comment]
Good finds, thanks. I'll have to work on this more after class.

For whatever reason the stock Android emulators don't mount SD cards as expected so I have to figure that out. It would make fixing all of this a lot easier.

**Comment by arkon** [comment]
@afollestad If you have some money lying around, you could pick up a Moto G for testing or something.

**Comment by afollestad** [comment]
Unfortunately I haven't had had a lot of time to work so I'm a broke college student lol

**Comment by arkon** [comment]
Those American tuition fees, huh? :sob:

**Comment by afollestad** [comment]
Haha yeah 😂

**Comment by afollestad** [comment]
@arkon can you test this again when you get the chance? I just pushed some code that in theory should only display the external storage shortcut if the phone reports it as mounted.

**Comment by arkon** [comment]
@afollestad Literally just finished an assignment. I'll get report back in a bit.

**Comment by arkon** [comment]
Unmounted the SD card and the app remains in the folder, breadcrumbs and nav drawer remain unchanged. Relaunched the app and the nav drawer entry is gone, but the app remains in the same directory (although that's #105).

Remounting the SD card also requires me to relaunch the app to see it in the nav drawer.

**Comment by afollestad** [comment]
Well good news that it goes away when the app is re-opened. So it looks like the `BroadcastReceiver` in `NavigationDrawerFragment` that receives the mount intents isn't receiving the intent broadcasts, or some other logic is wrong. But yeah the other stuff will come with #105, once I've verified that the broadcast receivers get notified correctly when the mounted state changes.

Thanks for the report though, making progress.

**Comment by arkon** [comment]
Tried it again. I think I might had to relaunch the app to make it go away because I was in the sdcard1 folder at the time. I tried it again from internal storage, and the nav drawer entry for External Storage immediately disappeared. Remounting didn't cause it to immediately come back though (relaunching works).

**Comment by arkon** [comment]
Although the nav drawer entry doesn't show up, you can of course manually navigate to /storage/sdcard1/ perfectly fine.

**Comment by afollestad** [comment]
Hmm, that's pretty weird. The navigation drawer operates independently so it shouldn't be effected by what directory you're in :scream: 

If you set a breakpoint at line 40 of `NavigationDrawerFragment`, does that line get called when you mount or unmount?

That reminds me, you have read/write access? Right? If you didn't, it would show a warning on startup.

**Comment by arkon** [comment]
I do have write access to my SD card, yeah.

**Comment by afollestad** [comment]
Awesome, getting close to production-ready.

**Comment by arkon** [comment]
Oh boy, I realized I can't have my phone connected to my computer via USB and mount/unmount at the same time and had to use wireless ADB. What a pain.

I also just put in a Log comment in the method, since I couldn't tell if the debugger was working over wireless or not.

It seems to have triggered once when I unmounted, and the "External Storage" entry disappeared (which made DCIM entry active -- another bug). It seems oddly unreliable.

**Comment by afollestad** [comment]
Lol, well you can, but you have to explicitly say which connection to use.

Oh yeah, debugging doesn't seem to work over wireless since there's too much of a lag time for loading the stack and stack variables.

Hmm, I wonder if I'm missing a needed intent when I set up the intent filter (**line 70** of `NavigationDrawerFragment`). Also, I think changing the selection there will come with #105, I'll add that to that issue.

**Comment by arkon** [comment]
Oh yeah, I can just disable MTP/PTP. Let me go try debugging it.

**Comment by afollestad** [comment]
Good idea, sounds good

**Comment by arkon** [comment]
Wait I lied, ADB doesn't work properly without MTP.

**Comment by afollestad** [comment]
Oh right, I never deal with that on my Nexus devices lol

**Comment by arkon** [comment]
I used to love having a SD card slot. :sob:

**Comment by afollestad** [comment]
Well, it's nice to have in situations like this :sweat_smile:

**Comment by arkon** [comment]
[Relevant?](http://stackoverflow.com/questions/7142987/media-mounted-broadcast-not-being-received)

**Comment by afollestad** [comment]
Unfortunately no, the file scheme is added on **line 74**

**Comment by arkon** [comment]
Hmm could it have anything to do with it being in `onResume` and not in `onCreate`, for example?

**Comment by afollestad** [comment]
It shouldn't onCreate() is only called the first time the app starts (well, the fragment). onResume() and onPause() will be called every time the app opens or closes, which is important because the broadcast receiver will cause a leak if it's not unregistered.

**Comment by arkon** [comment]
But if the app was just opened, would `onResume` be called so that the intent filters and broadcast receiver are registered?

**Comment by afollestad** [comment]
Yeah, if it's triggered when it unmounts like I believe you said above, that should verify that works too.

Hmmmm.

**Comment by afollestad** [comment]
Once this and https://github.com/afollestad/cabinet-issue-tracker/issues/105 are done, we can publish an update.

@arkon @plusCubed

**Comment by afollestad** [comment]
And possibly https://github.com/afollestad/cabinet-issue-tracker/issues/110

**Comment by afollestad** [comment]
@plusCubed @arkon and another one which you've already commented on lol

**Comment by afollestad** [comment]
Closing this for now.
